{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "operator.name" . }}-pod-webhook
  labels:
    {{- include "operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions: [v1]
  clientConfig:
    caBundle: {{ .Values.webhook.caBundle | default "" | quote }}
    service:
      name: {{ include "operator.name" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
  failurePolicy: Ignore
  name: mpod.percentagepolicy.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - {{ .Release.Namespace }}
      - kube-system
  rules:
  - apiGroups: [""]
    apiVersions: [v1]
    operations: [CREATE]
    resources: [pods]
  sideEffects: None
{{- end }}
