---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.percentagepolicy.io
  resources:
  - percentageresourcepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.percentagepolicy.io
  resources:
  - percentageresourcepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - policy.percentagepolicy.io
  resources:
  - percentageresourcepolicies/status
  verbs:
  - get
  - patch
  - update
